name: Deployment Workflow

on:
  push:
    branches:
      - "master"
    tags:
      - "release-*"

jobs:
  build_and_publish_image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: docker build --target deploy -t docker.pkg.github.com/mihaxxx/mmcs_schedule_bot/bot:1.0.$GITHUB_RUN_NUMBER .
      - name: Docker build latest
        run: docker build --target deploy -t docker.pkg.github.com/mihaxxx/mmcs_schedule_bot/bot:latest .
      - name: Docker Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u MihaxXx --password-stdin
      - name: Docker publish
        run: docker push docker.pkg.github.com/mihaxxx/mmcs_schedule_bot/bot:1.0.$GITHUB_RUN_NUMBER
      - name: Docker publish latest
        run: docker push docker.pkg.github.com/mihaxxx/mmcs_schedule_bot/bot:latest

  deploy_image:
    runs-on: ubuntu-18.04
    env:
      TG_TOKEN: ${{ secrets.TG_TOKEN }}
      VK_TOKEN: ${{ secrets.VK_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Deploy image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          envs: TG_TOKEN, VK_TOKEN, GITHUB_TOKEN, GITHUB_RUN_NUMBER
          script: |
            echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u MihaxXx --password-stdin
            docker stop mmcs_bot
            docker run --rm -d --name mmcs_bot --restart unless-stopped -v /workload/mmcs_bot:/data --env \
              MMCS_BOT_PATH_TO_DB=/data \
              MMCS_BOT_TG_TOKEN=$TG_TOKEN \
              MMCS_BOT_VK_TOKEN=$VK_TOKEN \
              MMCS_BOT_GROUP_URL=mmcsschedulebot \
              docker.pkg.github.com/mihaxxx/mmcs_schedule_bot/bot:1.0.$GITHUB_RUN_NUMBER
